steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  - name: gcr.io/cloud-builders/gcloud
    args: ['gcloud', 'app', 'deploy', '$_YAML_FILE']
